version: 2
project_name: portkiller

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

# 1. HOMEBREW (macOS/Linux)
brews:
  - name: portkiller
    repository:
      owner: ayushsharma74
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/ayushsharma74/portkiller"
    description: "Simple TUI to kill open ports, written in Go."
    install: |
      bin.install "portkiller"

# 2. SCOOP (Windows Devs)
scoops:
  - name: portkiller
    repository:
      owner: ayushsharma74
      name: scoop-bucket # Create this repo on GitHub
    directory: bucket
    homepage: "https://github.com/ayushsharma74/portkiller"
    description: "Simple TUI to kill open ports."
    license: MIT

# 3. WINGET (Windows Official)
winget:
  - name: portkiller
    publisher: ayushsharma74
    license: MIT
    copyright: Copyright (c) 2026 Ayush Sharma
    homepage: "https://github.com/ayushsharma74/portkiller"
    short_description: "Simple TUI to kill open ports"
    publisher_url: "https://github.com/ayushsharma74"
    package_identifier: "ayushsharma74.portkiller"
    # To fix the error, we simplify the repository block
    repository:
      owner: microsoft
      name: winget-pkgs
      branch: master

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
